version: '3.8'

services:

  todo-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: todos
    volumes:
      - todo-db-data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - todo-network
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin status -uroot -p$$MYSQL_ROOT_PASSWORD --protocol=TCP"]
      interval: 4s
      timeout: 10s
      retries: 10

  setup-db:
    build: 
      context: .
      dockerfile: setup-db/Dockerfile
    environment:
      MYSQL_HOST: todo-db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: todos
    depends_on:
      todo-db:
        condition: service_healthy
    networks:
      - todo-network

  web-api:
    build: 
      context: .
      dockerfile: web-api/Dockerfile
    environment:
      MYSQL_HOST: todo-db
      MYSQL_USER: root
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: todos
    ports:
      - "8000:8000"
    depends_on:
      todo-db:
        condition: service_healthy
      setup-db:
        condition: service_completed_successfully
    networks:
      - todo-network

volumes:
  todo-db-data:

networks:
  todo-network:
